### ISSUE TITLE
Cannot get node values when getting node from getChildren function.

### ISSUE THREAD

**Issue by BananaEgg** [cyber-geiger/toolbox-storage#46]
When I directly get the node from the storage the values exist, but now when getting first the parent node and then the children.

This works:
 ```dart
 void getChild(path) async {
    print('Trying to get the data node');
    try {
      Node node = await storageController!.get(path);
      Map<String, NodeValue> nodeValues = await node.getValues();
      print(nodeValues.values.first);
    } catch (e) {
      print('Failed to retrieve the data node: ' + e.toString());
    }
  }
```

But not this:
```dart
 void getParentThenChildren(path) async {
    print('Trying to get the data node');
    try {
      print('Found the data node - Going to get the data');
      Node node = await storageController!.get(path);
      Map<String, Node> sensorReportNodes = await node.getChildren();
      for (var report_node in sensorReportNodes.values) {
        Map<String, NodeValue> nodeValues = await report_node.getValues();
        print(nodeValues.values.first);
      }
    } catch (e) {
      print('Failed to retrieve the data node: ' + e.toString());
    }
  }
```
  
  I've got a working sample if needed.

**Comment by tschai-yim** [comment]
Added a test that reproduces this issue. It only occurs when using the `SqliteMapper`.

PS: you can format code by surrounding it in three \`\`\` and optionally specifying the language after the first three.
Like:
```
```dart
void main() {
  print('hello world');
}
```⠀
```
results in
```dart
void main() {
  print('hello world');
}
```

**Comment by BananaEgg** [comment]
@tschai-yim Thanks for you comment, I updated it.
Can you please elaborate on the usage without SqliteMapper?

**Comment by tschai-yim** [comment]
I just fixed it with d24ed4b6895115df09eb6069d269b1b081f34208. It was an issue in `NodeImpl` so not mapper-specific.  The `DummyMapper` returns fully loaded nodes while the `SqliteMapper` only returns skeletons. For now, you can just use the `DummyWrapper` if you don't need persistence and don't want to use the version on `development`.

**Comment by BananaEgg** [comment]
@tschai-yim, Do you know when would this version of the storage be updated in the Geiger API?

**Comment by tschai-yim** [comment]
The fix should be included in [0.6.43](https://pub.dev/packages/geiger_localstorage/versions/0.6.43). Else I'd have to ask Martin.

**Comment by BananaEgg** [comment]
Can you please update what is happening with this, it is still not working with geiger API v0.7.5

**Comment by martingwerder** [comment]
As of mail from BananaEgg the issue persists

**Comment by tschai-yim** [comment]
So the issue also occurred for serialized nodes as they didn't get marked as skeletons. We'll release the patched version soon. 

Next time please specify what `StorageController` you're using, as I tested the original patch only on this repo (meaning only the `GenericController` with different `StorageMapper`s).

**Comment by martingwerder** [comment]
published as 0.7.6. Does that solve your issue?

**Comment by BananaEgg** [comment]
Still not working, both the master and the plugin are using 0.7.6

**Comment by BananaEgg** [comment]
https://github.com/BananaEgg/plugin_test_child_node

**Comment by tschai-yim** [comment]
While this example wasn't minimal at all (no master, has everything wrapped in an abstraction, has 4 different targets) I was able to track down the issue on our side and [fix](https://github.com/cyber-geiger/toolbox-communicationApi/commit/c30c95a0f75d92f873341bdd42f17f5a2a7f24ed) it. We'll release it soon.

btw. It would have been useful if you provided the expectation it throws when you call `node.getValues()`:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      NodeImpl._init (package:geiger_localstorage/src/db/data/node_implementation.dart:156:36)
#1      NodeImpl.getValues (package:geiger_localstorage/src/db/data/node_implementation.dart:321:11)
#2      GeigerApiConnector.getParentThenChildren (package:geiger_test_plugin/geiger_connector.dart:119:61)
<asynchronous suspension>
```

**Comment by martingwerder** [comment]
published as 0.6.48.

**Comment by BananaEgg** [comment]
I found that the issue persists in some cases.
I cannot track the reason, bot it seems to be a side effect, Even a different plugins non related  storage change can brake this functionality.
There's no error message, the function just doesn't find child nodes.

**Comment by Jet132** [comment]
I've added an isolate-based test on geiger_api (https://github.com/cyber-geiger/toolbox-communicationApi/commit/48defa278365fb86ba8602500b0cea8128ba50b8) but was not able to reproduce it. Perhaps it has something to do with how node deserialization uses the last created controller blindly: [lib/src/db/data/node_implementation.dart](https://github.com/cyber-geiger/toolbox-storage/blob/development/lib/src/db/data/node_implementation.dart#L741-L742=)

We'll take a closer look. Could you in the meantime provide a [MRE](https://stackoverflow.com/help/minimal-reproducible-example)? Else clearly resolving this issue will become nearly impossible.

**Comment by tschai-yim** [comment]
I've added an isolate-based test on geiger_api (https://github.com/cyber-geiger/toolbox-communicationApi/commit/48defa278365fb86ba8602500b0cea8128ba50b8) but was not able to reproduce it. Perhaps it has something to do with how node deserialization uses the last created controller blindly: [lib/src/db/data/node_implementation.dart](https://github.com/cyber-geiger/toolbox-storage/blob/development/lib/src/db/data/node_implementation.dart#L741-L742=)

We'll take a closer look. Could you in the meantime provide a [MRE](https://stackoverflow.com/help/minimal-reproducible-example)? Else clearly resolving this issue will become nearly impossible.

**Comment by BananaEgg** [comment]
I'm working on the MRE, something seems to have changed, now I see the issue might not be related to the getChildren function, it appears also after connecting a second plugin the first plugin cannot get the Node even when trying directly.
There's a timeout message:

```
I/flutter ( 6072): Trying to get the data node
I/flutter ( 6072): Failed to retrieve the data node: StorageException:Remote call failed at
I/flutter ( 6072): #0      new SerializedException
package:geiger_localstorage/src/storage_exception.dart:39
I/flutter ( 6072): #1      new StorageException
package:geiger_localstorage/src/storage_exception.dart:117
I/flutter ( 6072): #2      PassthroughController._remoteCall
package:geiger_api/…/storage/passthrough_controller.dart:85
I/flutter ( 6072): <asynchronous suspension>
I/flutter ( 6072): #3      PassthroughController.get
package:geiger_api/…/storage/passthrough_controller.dart:91
I/flutter ( 6072): <asynchronous suspension>
I/flutter ( 6072): #4      GeigerApiConnector.getParentThenChildren
package:geiger_test_plugin_2/geiger_connector.dart:113
I/flutter ( 6072): <asynchronous suspension>
I/flutter ( 6072):
I/flutter ( 6072): cause:
I/flutter ( 6072): CommunicationException:timeout reached while waiting for reply at
I/flutter ( 6072): #0      new SerializedException
package:geiger_localstorage/src/storage_exception.dart:39
I/flutter ( 6072): #1      new CommunicationException
package:geiger_api/…/exceptions/communication_exception.dart:9
I/flutter ( 6072): #2      Listener.waitForResult (package:geiger_api/src/communication/communication_helper.d
I/flutter ( 6072): Failed to retrieve the data node: StorageException:Remote call failed at
I/flutter ( 6072): #0      new SerializedException
package:geiger_localstorage/src/storage_exception.dart:39
I/flutter ( 6072): #1      new StorageException
package:geiger_localstorage/src/storage_exception.dart:117
I/flutter ( 6072): #2      PassthroughController._remoteCall
package:geiger_api/…/storage/passthrough_controller.dart:85
I/flutter ( 6072): <asynchronous suspension>
I/flutter ( 6072): #3      PassthroughController.get
package:geiger_api/…/storage/passthrough_controller.dart:91
I/flutter ( 6072): <asynchronous suspension>
I/flutter ( 6072): #4      GeigerApiConnector.getChild
package:geiger_test_plugin_2/geiger_connector.dart:131
I/flutter ( 6072): <asynchronous suspension>
I/flutter ( 6072):
I/flutter ( 6072): cause:
I/flutter ( 6072): CommunicationException:timeout reached while waiting for reply at
I/flutter ( 6072): #0      new SerializedException
package:geiger_localstorage/src/storage_exception.dart:39
I/flutter ( 6072): #1      new CommunicationException
package:geiger_api/…/exceptions/communication_exception.dart:9
I/flutter ( 6072): #2      Listener.waitForResult
package:geiger_api/…/communication/communication_helper.dart:42
I/flutter ( 6072): <a
```

**Comment by BananaEgg** [comment]
Found the issue on my side, both plugins where preparing the path for the node, so I guess there was some ownership conflict that disrupted the getChildern function.
